services:
  - type: web
    name: fertilizer-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5020
    plan: free
